# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/zww/Documents/College/2022SP/HDL/HdlMicroProcessor/HdlMicroProcessor.srcs/sources_1/ip/call_stack/call_stack.xci
# IP: The module: 'call_stack' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/zww/Documents/College/2022SP/HDL/HdlMicroProcessor/HdlMicroProcessor.gen/sources_1/ip/call_stack/call_stack_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'call_stack'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/zww/Documents/College/2022SP/HDL/HdlMicroProcessor/HdlMicroProcessor.srcs/sources_1/ip/call_stack/call_stack.xci
# IP: The module: 'call_stack' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/zww/Documents/College/2022SP/HDL/HdlMicroProcessor/HdlMicroProcessor.gen/sources_1/ip/call_stack/call_stack_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'call_stack'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
