/*
Module - Flags Register
Author - Zach Walden
Last Changed - 2/1/22, 3/28/22
Description - Register that stores flags generated by the alu in the previous cycle.
Parameters - All Parameters are self explanatory.
*/

module flags_register(
	input clock,
	input nreset,
	input [2:0] new_flags,
	output reg [2:0] cur_flags = 0
);

	always @ (posedge clock)
	begin
		if(nreset == 1'b0)
		begin
			cur_flags <= 0;
		end
		else
		begin
			cur_flags <= new_flags; //This may be the incorrect procedure depending on what type of stall occurs.
		end
	end

/*
// the "macro" to dump signals
`ifdef COCOTB_SIM
initial begin
  $dumpfile ("flags_register.vcd");
  $dumpvars (0, flags_register);
  #1;
end
`endif
*/
endmodule
