# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/zww/Documents/College/2022SP/HDL/HdlMicroProcessor/HdlMicroProcessor.constraints/Arty-S7-50-Master.xdc

# IP: ip/program_memory/program_memory.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==program_memory || ORIG_REF_NAME==program_memory} -quiet] -quiet
