/*
Module - Flags Register
Author - Zach Walden
Last Changed - 2/1/22
Description - Register that stores flags generated by the alu in the previous cycle.
Parameters - All Parameters are self explanatory.
*/

module flags_register(
	input clock,
	input nreset,
	input stall,
	input [2:0] new_flags,
	output [2:0] cur_flags
);

	reg [2:0] value = 0;

	always @ (posedge clock)
	begin
		if(nreset == 1'b0)
		begin
			value <= 0;
		end
		else if(stall == 1'b0)
		begin
			value <= new_flags;
		end
		else
		begin
			value <= value; //This may be the incorrect procedure depending on what type of stall occurs.
		end
	end

	assign cur_flags = value;

// the "macro" to dump signals
`ifdef COCOTB_SIM
initial begin
  $dumpfile ("flags_register.vcd");
  $dumpvars (0, flags_register);
  #1;
end
`endif
endmodule
